export const GET_CUSTOMERS = "GET_CUSTOMERS"
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
export const GET_TASKS = "GET_TASKS"
export const GET_CATEGORYLIST = "GET_CATEGORYLIST"
export const ADD_TASK = "ADD_TASK"

export const BUY_STOCK = "BUY_STOCK"
export const SELL_STOCK = "SELL_STOCK"
export const DEPOSIT_MONEY = "DEPOSIT_MONEY"
export const WITHDRAW_MONEY = "WITHDRAW_MONEY"


